---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - blocky
  - dex
  - external-dns
  - ingress-nginx
  - k8s-gateway
  - nut-server-garage
  - oauth2-proxy
  - singularity
