---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - blocky
  - cert-manager
  - coredns
  - dex
  - etcd-extdns
  - external-dns
  - external-dns-cloudflare
  - ingress-nginx
  - nut-server-garage
  - oauth2-proxy
