apiVersion: v1
kind: Secret
metadata:
    name: miniflux-init-db
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:a/t5MwgoN6c=,iv:h3qvk32JwM45ovNjWDeffUBzcS4ZbacqtXK+lJYbRow=,tag:I0LoRSA9u23iFOqoPX3kEQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:EEhS52EpJMq3pEvx8hU3+reI+OIkuhVDydoFGoP9gefGiuepXUr4lw==,iv:yPuqQQHjOIvdh9nvm0HP1eyg1/besyiuFvo0ZrjEtIY=,tag:EYsmZrHfKkfNRFWlC+M2bA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:QKOCTfJFuiE=,iv:ia3yG9RvUp+Q/bba/T+fABqzg2O9DDQUWFtbs2umNPg=,tag:8EFS0p5dHvf5b+htkBusWw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:i3Bkx9Bip7J0eA87Xporu627zUo=,iv:9xNQuQnwdDLrWG1fMr28odiN2P5fiqJQ9ac3KPz9XOc=,tag:2l3GFww7kwLaLvUCiNvXDg==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:t6sYII4YeKRq0UGLqMqcOeS3pXI=,iv:203LbaBFtDyDrms/1QqqJTLKwC546ysWbWUlX8lk2pE=,tag:RjBSFbzee+TwoYzj7lBASw==,type:str]
sops:
    age:
        - recipient: age1xrxcj4d3zj8pnnyysph9qpve8stj8wr9dk7y0nq8ns4nukcruyxq5cc5at
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UDJ2RTNDdFRqdXNvWHdw
            UU51L3FxMkY0ZXVjY01QbTRPcVVkZzZwQ0ZjCnFVNmExZENaYm9ZbmllTVN2Y3I3
            dzk2eVp4OXhDTkhqMHpQZng4b1hyZ0UKLS0tIFF0cWY1Szg4TkM3WXJNcFNqVUwv
            OTFOc0svT0JxZXFBVnB1a0FZUmJ0YjgK2N7zrzOv9UBZQkAs37HriBBNKFtGFUId
            MJIbwnSbf/DdYFHTt4f5Oo6m0ENo9rbJ2bkTBX3mrMfkr3WGdubx2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T19:22:52Z"
    mac: ENC[AES256_GCM,data:V2cq2pgMbWfa0kzWdcT2l9Hk8QLhwiopFPHuSHz36kfU53CkzItt9IPLywrPGRgTs/k0/moNMD+rX3KxvHuq0Mftc4/3CxVIsC+g0Fi0R3DN0Lyrz+rhKdkX5lVdOQXlsGGoB8GjHC0tsDZIsIOu0FdAGEDcZrh6Deldrt0/42s=,iv:zwE8om2E3FAfs2wZYcammwXgurzQ2s4h5gR+pEVvs40=,tag:r8h2awGkDVIb7Va4IA4ZYw==,type:str]
    pgp:
        - created_at: "2025-11-09T19:17:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DopS/VjtMxJoSAQdASz8+DRViihuSBoZFcOMICCGNbO6tsYWQESKSENLQWEow
            mLSJWy8b/YydocbuaKwvrT1WIFqbZ342fP/enjvNJOxPRHBbcsKTGehtZHQDaczT
            0l4BT/6RxJOa73zElPPQktJJmUwKRooEmztRkS+4R3+keZBIATwllU0iG4JzprKt
            ocWBbtPSBzweI0D4GoIa7dn26wktg8PeJvddcEfzgV7qCxH2xXGiAdwbTlEDQfzz
            =pNfI
            -----END PGP MESSAGE-----
          fp: 86170CE5CB464ADDC6BE8E597450F180356132B6
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
