apiVersion: v1
kind: Secret
metadata:
    name: miniflux
stringData:
    ADMIN_USERNAME: ENC[AES256_GCM,data:UI8IoVE=,iv:8zS3RSs2BnQRtJ8Lvk2bC5Z8qNUNUejxw8AyI9BYVZY=,tag:KRZ0rlv13AMO1cGefTBz0A==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:VytaiyfzBTNnz+zH4p7L2IUaLEE=,iv:FwGQqYTi+tJbFFQ8GWAzRAWNWM/XvDC87I6xmwLh8qU=,tag:f5kVDRhFYL96/a94WcIh7Q==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:FuJgxvUbrlGBXEePh8daPZpv0NxWR2J+Edbai6KqzEg+reHPzZgQV5aKwx/DpDxPB9BRTp/FeEoyBPd2Y79eqwjG4Ksif3iIAA8/5ieTsFzuJhbsBRX1VNFfal+X5YYk+p8SEconvkgO4Q==,iv:FEKUjp0JnbpRonayJ/FpLyFX5k/skS6qEZwoKTf8EYw=,tag:ItPTBZz23zE7aFFKbYBO4A==,type:str]
    OAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:CQOaKoB6GWbkZRfqq01ysZxSRAQnJuZdwpB4xRqr2yVXLyiWouRxDAUicPrvuyctpSGOO1Hffux8x5d4eSMCrs/KvYiFSvW/,iv:nVVEnnKabgx6BPKMqq4v7nW0jeairTwwPm1WmcYb9jc=,tag:p0lhg6E0l1VECaHcYnugfA==,type:str]
sops:
    age:
        - recipient: age1xrxcj4d3zj8pnnyysph9qpve8stj8wr9dk7y0nq8ns4nukcruyxq5cc5at
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSHJnbDJLNUNUR0ExRWpY
            bjVsRTdrNlhtekhxQjRGd3dueDFZTnErMVdVClI3YytLYU9CV2Z5Unh6TU5NT3FI
            U2pQVGI4dE1zSERNK2RWcjl2TnJFUEkKLS0tIFhXdHNTQzZ4RmhXeVlGbHpQam5h
            WE9FYU1McFFBL21DK2kyb0lsSnVhUlEKMUjZwD/1kZwqu/arGcGJoRsuKYPsek0G
            xik7MWxby+9U6Fkngw5CaZxQGI6XLgbmdVPN+hUJ+UNmKS5DMp/e4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T19:18:28Z"
    mac: ENC[AES256_GCM,data:ERvpEjgHWp9gaYXPBGAnbIo4f0zDn+B99dT8FmGRrTSwTYJk/P+tsAccyTZOPs8xs+3Mks5SSWvDrHQoeOobc10McfUfqWDzDHMCU8bpESkuHqMzLTDSMaicbj5FiSOtt2eN1mRC7YZCCejZblYP2mnuMV2RjKjqhKtG4uPixc0=,iv:3RJOunKCDC4KfggIFcyPN0xJCGOaeZYT5lb+Mizv6QA=,tag:BkRLAdfJJgsONE98W9khMA==,type:str]
    pgp:
        - created_at: "2024-06-22T10:58:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DopS/VjtMxJoSAQdAGyo6efV031zgz1kcWhfecsXxcbOI6lYDDR7CrVUZORsw
            8Hhnyd7izF2Z8dPSQLvI/FL0ydiNE6DPnFBtxg9eyxO3IsaqskNnyBtT48626hXF
            0l4BdHWZHNPigfJEa+cAVrazSClleI4Ucs8KRljxwP21A/ukA3Ypj6a1cmWtQUer
            b04SBWJ2eMOtvk0wq8dOqnVVZI3P1p2rs+05eZv2o0vK13Zrx9I0Mp5AP3kwN1eW
            =lBFI
            -----END PGP MESSAGE-----
          fp: 86170CE5CB464ADDC6BE8E597450F180356132B6
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
