# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: miniflux
stringData:
    #ENC[AES256_GCM,data:WnE6Bs+mNuLM,iv:Oa9V2dyDWOaLuQA7K0V7AQrdCPXmWN8ZdEGbFhGn52E=,tag:s8TtdPuXs/QwIYEVlDVLxw==,type:comment]
    ADMIN_USERNAME: ENC[AES256_GCM,data:UI8IoVE=,iv:8zS3RSs2BnQRtJ8Lvk2bC5Z8qNUNUejxw8AyI9BYVZY=,tag:KRZ0rlv13AMO1cGefTBz0A==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:VytaiyfzBTNnz+zH4p7L2IUaLEE=,iv:FwGQqYTi+tJbFFQ8GWAzRAWNWM/XvDC87I6xmwLh8qU=,tag:f5kVDRhFYL96/a94WcIh7Q==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:FuJgxvUbrlGBXEePh8daPZpv0NxWR2J+Edbai6KqzEg+reHPzZgQV5aKwx/DpDxPB9BRTp/FeEoyBPd2Y79eqwjG4Ksif3iIAA8/5ieTsFzuJhbsBRX1VNFfal+X5YYk+p8SEconvkgO4Q==,iv:FEKUjp0JnbpRonayJ/FpLyFX5k/skS6qEZwoKTf8EYw=,tag:ItPTBZz23zE7aFFKbYBO4A==,type:str]
    OAUTH2_CLIENT_SECRET: ENC[AES256_GCM,data:CQOaKoB6GWbkZRfqq01ysZxSRAQnJuZdwpB4xRqr2yVXLyiWouRxDAUicPrvuyctpSGOO1Hffux8x5d4eSMCrs/KvYiFSvW/,iv:nVVEnnKabgx6BPKMqq4v7nW0jeairTwwPm1WmcYb9jc=,tag:p0lhg6E0l1VECaHcYnugfA==,type:str]
    #ENC[AES256_GCM,data:hZDdzzPXTEq1QCOtMdM=,iv:bQWr9i2Uad+481oGwZaIMgJH6Zc0yRGBsRhI5kYA68A=,tag:C+M7cN+0nXGBrK3R3ZvaqQ==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:ggwfRjsDzGc=,iv:TW9zXsCFt4OC3Vm6KgJ0EbjgcAozAphKPfjoT2fLHAw=,tag:A/sE7qwrzY63/Uq58sWtHQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:CUJQpGSkUMiKW3pj3GPvwotF3qiGomrV+Rd2NKHIGLwOEebc7akwJg==,iv:rIS/7SJdDcRbynArYG0RAxxMSGJW4T7e2dshL2QEicg=,tag:xi/UYP3o0Pawz5eTycyzsg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:bkA7zVfs1ho=,iv:gYI/J/iigaPXYBdD8FmHYRFZBkmTc7UzIm0pBnUA9dw=,tag:/8gT7oVKiTFZYQ2E2hShSA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:f/31PVcrcgUvnuDNQ49Zr83I2FI=,iv:cFI2s2633hMZMt0ASg7/RFpyQ/AT8CI+qHOFG2+oKew=,tag:96mUatIB7AUwUlBILIAFBg==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:3DikLTky3cGuKeEDVDQhdt/uw0A=,iv:xvAs0LP2keDffR4CTNkbXapNUJXu/tYE2P1hO0ehY3g=,tag:YafNe79vJJdbEJkuhf8RQg==,type:str]
sops:
    age:
        - recipient: age1xrxcj4d3zj8pnnyysph9qpve8stj8wr9dk7y0nq8ns4nukcruyxq5cc5at
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSHJnbDJLNUNUR0ExRWpY
            bjVsRTdrNlhtekhxQjRGd3dueDFZTnErMVdVClI3YytLYU9CV2Z5Unh6TU5NT3FI
            U2pQVGI4dE1zSERNK2RWcjl2TnJFUEkKLS0tIFhXdHNTQzZ4RmhXeVlGbHpQam5h
            WE9FYU1McFFBL21DK2kyb0lsSnVhUlEKMUjZwD/1kZwqu/arGcGJoRsuKYPsek0G
            xik7MWxby+9U6Fkngw5CaZxQGI6XLgbmdVPN+hUJ+UNmKS5DMp/e4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-06T07:56:27Z"
    mac: ENC[AES256_GCM,data:qLvVMlJYo5ab4cp2kXgrxPzKyxDBIMhIaChxif+YFiBNTk5ogymI5PjK/EMxJwt/2S7sYAwDS71IXMfs7ANf69jz7U29wphCPfXCGdsjFbfQmW+UmFA7ANLG03FZpTjj5PIVvn+zKl9M7zXVdtbzBAocpu3YBgEX2Jun3gReHng=,iv:1TQQ7/VM+n3ICs3t8xja36avXpChqI7VtajUVy2M6mk=,tag:47AH+3YeK+IwSehQZRef9Q==,type:str]
    pgp:
        - created_at: "2024-06-22T10:58:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DopS/VjtMxJoSAQdAGyo6efV031zgz1kcWhfecsXxcbOI6lYDDR7CrVUZORsw
            8Hhnyd7izF2Z8dPSQLvI/FL0ydiNE6DPnFBtxg9eyxO3IsaqskNnyBtT48626hXF
            0l4BdHWZHNPigfJEa+cAVrazSClleI4Ucs8KRljxwP21A/ukA3Ypj6a1cmWtQUer
            b04SBWJ2eMOtvk0wq8dOqnVVZI3P1p2rs+05eZv2o0vK13Zrx9I0Mp5AP3kwN1eW
            =lBFI
            -----END PGP MESSAGE-----
          fp: 86170CE5CB464ADDC6BE8E597450F180356132B6
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
