---
ansible_become: true  # noqa: var-naming[no-role-prefix]
os_timezone: Europe/Paris
os_packages:
  install:
    - apt-transport-https
    - arptables
    - ebtables
    - nfs-common
    - open-iscsi
  remove:
    - apparmor
    - cloud-init
    - plymouth
    - snapd
    - ufw
