---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./secret.sops.yaml
  - ../../../../templates/persistence
  - ../../../../templates/gatus/guarded
configMapGenerator:
  - name: frigate-config
    files:
      - ./resources/config.yml
generatorOptions:
  disableNameSuffixHash: true
