apiVersion: v1
kind: Secret
metadata:
    name: autobrr-init-db
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:drAo1SGEQg==,iv:9lBJjsZZRzTXmiY+Qlz3ygWQna+aMEr1WsLGljMFAic=,tag:etbRCfVQSuYDxRMdXE3dcQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:EUd682VhEgv/+vS62Ok602S6H5TnSP8tDdFgQFbZEPOgN1NmnU9DLg==,iv:bdWnJeyx1D3ayAH+Sw9ziQLJJ7fM3wAcNQG1CZY78dM=,tag:klP1NZ5OelyD22JEo9OyBQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:IK/Z9cmO1w==,iv:aDtLNJsf8Xjcmcu+go/sD7iYOF/44KDpvhO0CZjQUsc=,tag:nVN3M2gmmsLyR48IkzWFyA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:QtpOVxNEJGlg3enfRiFQNcBQPNo=,iv:rk6zbTSGJYHPKjo7Jb2QVVzBw7fgQdFM12oqyb7w2RE=,tag:2mhw63w4WE68eZJIMtrP3w==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:cpdp6IdUJtgLoxy2lLwdpWnQNW0=,iv:ALgc9Q1PlIGyjWjU+5Hd9qxNM8AI7cQ+4uZcaWFKPUM=,tag:M2e4bDu/MbxJXDpAM2tcGA==,type:str]
sops:
    age:
        - recipient: age1xrxcj4d3zj8pnnyysph9qpve8stj8wr9dk7y0nq8ns4nukcruyxq5cc5at
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzeGp4THRLYTdybTd4L2ts
            dUh3SEdWcG5hS3ZkRTEybXhGdDQvaXNaajJFCllqVWdiQjd0Vjg5M2dVdFlvTVBj
            VWVCNUdqLzVwVWdJSHJ3Z0RWVkJlVlEKLS0tIEcvOHZNUVFtS2U5Z0wyOHorckRr
            dkNBMisra1RPUlZTRHZZNkNtSFVxQkkKZ+cRUe0A5UUXSGagXK3pT4fGHlWLgd6/
            GkuBAS/VgS8hzKbbgmh1V5iGXA5tbZq+peadgce7pN7Ht0CP+nohjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T19:23:10Z"
    mac: ENC[AES256_GCM,data:5R+7XCfNEgHHGF9SDqPqmd9KoRbLAUOoMU0wxHmW4D2sEX0Sa4B3mSNZLMBMmLxyLfS6FRju+WYYHAS+V0cpHruVg1ojrus6h5JKlNB/l5sJDV6Eog6Sk592fTyyOpceQyr44mE0Sv4vO9gC6Duf1eS+fiCQXIsUwLgNgg5UFo8=,iv:kd/DopIo837/P4U6v37K9E3I0JAeW0nNPr73KY6+QmE=,tag:FW/o5V8ovtRAOQ786TRjgA==,type:str]
    pgp:
        - created_at: "2025-11-09T19:16:30Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DopS/VjtMxJoSAQdAoTUVIa2jYOjpEWiFkxdBLp1I6jgCM2rnWEpn8gUqX2gw
            oZ5uVs9uXTMI4J687N0OpqmyEm2ePSCovzsDhpC1Of8Bdc+HGU15KjkJlz3i6sEn
            0l4B9jrnJIYpmbxEnXeyBhNdwH1KYmzz91mLFhDwcaHuSNYO4AkwGlgYBArGk8EE
            w4PqjYpYvX1UYg/LLH8EaUp+OWccpniW7qefOcEQfWq3GtKehfZjz+kqtLDftBNT
            =jozu
            -----END PGP MESSAGE-----
          fp: 86170CE5CB464ADDC6BE8E597450F180356132B6
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
