# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: autobrr
stringData:
    #ENC[AES256_GCM,data:eCFiQfBrKwk=,iv:rvjyFYBgSAOTxd2e+TqLFDb4Ps+HtQJi7OQdjAXe73o=,tag:nnvvnKzoJRcsF7RUUAo1eA==,type:comment]
    AUTOBRR__DATABASE_TYPE: ENC[AES256_GCM,data:RpeNOVJKCc8=,iv:JJvHfGKa+uwUxz8r/K3VW5G7kFyXEs8wCSNLOTXLktU=,tag:cN2FZKv5++21CXMobnIDTg==,type:str]
    AUTOBRR__POSTGRES_DATABASE: ENC[AES256_GCM,data:aYlHayM8jw==,iv:LKz1/dtkbRwiF1BC/ZG9m7wMs3bLbVx1Tpe6g8ca+hk=,tag:0zXPEqlfs2RO5mr4SyBH6g==,type:str]
    AUTOBRR__POSTGRES_HOST: ENC[AES256_GCM,data:/vbRLit2av4+aqisIEtJeuuCd8GRdWEQcgfxETRheEfvvYcbBP270w==,iv:6MfYSxvUA9V7ER/4QTdrv1e4CMQ6RErfNwXtlIgf8VE=,tag:p5soPAgIPHqDxWIyJkYA/Q==,type:str]
    AUTOBRR__POSTGRES_USER: ENC[AES256_GCM,data:Bv8E/ZLFjA==,iv:0OSktVrL+kgNK5MdI/IxAquiKrf0P/ceL5mgA2d159E=,tag:xhLSuZvYC3DwybmzZj7ORQ==,type:str]
    AUTOBRR__POSTGRES_PASS: ENC[AES256_GCM,data:WktkOEeefDfZcm94QMJHyjkAKsc=,iv:Vj2FxoNtRKRz1fLy8T6dqgh3buh3sYTBxXokjmLKzgI=,tag:9AB5uxvlY2QuvRg66RPL4g==,type:str]
    AUTOBRR__POSTGRES_PORT: ENC[AES256_GCM,data:VHA7/Q==,iv:Ff6V1fl3H5/daagwFpTOdqxInj8nV5iCvPaiiw4dMBI=,tag:DhNIrKIwVyutxjl0utB91A==,type:str]
    AUTOBRR__SESSION_SECRET: ENC[AES256_GCM,data:yM4CbyRlviKi4w9GjBs4bpIGlw8IoFp7ZUgSfBt95qLYQdjop0DKDZ7dHnBcTST8WK+8UxK7AWgCYdcO7B9f2w==,iv:lVlhjeHc8fd4DCXgxXzOcz4cgNQRvWizZZJDpui8bs8=,tag:oYWEf7edlr/Gr3BudOFaKw==,type:str]
    AUTOBRR__OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:uAxt1Y4LrY5OXudFlHs62u1f0hgv+8vLBjhTTwC5x1jSI9DZi0fPRmJSObw3R1nDCecnju3QaNraoJfGlpjF4fMVrB0OV9lr,iv:Q0X/GvzPkNFNm7mJufWW97ShfmWikK9xBXLx/lVnb/U=,tag:nC2JPi83RZD44vzCeAOCTg==,type:str]
    #ENC[AES256_GCM,data:hZDdzzPXTEq1QCOtMdM=,iv:bQWr9i2Uad+481oGwZaIMgJH6Zc0yRGBsRhI5kYA68A=,tag:C+M7cN+0nXGBrK3R3ZvaqQ==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:y52ZXCnpVw==,iv:/9h27phJdesvBoYPA43fbsinIfXIlG7DBVULMguX8B0=,tag:iivvnchjrneFtkUMAjN/tA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:bbAfPMEyvLfBbeXdd0GbMnlI2RJoZUcOprvXxCiSWK5G58CsP60Hbg==,iv:k8BlCZ3sgUO6ZBg77g1mh9kw24NCIgW3r3iSF5ykCBI=,tag:b6hvOOU1tK7EIrTovhQBIQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:+3vXCBvWgw==,iv:v1jDzoCpP74Tl+13VIFlM45Dgbh4SV91atbQZmSYOXs=,tag:IqAvFNKrIWeTYdJnTPzuow==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:MosOUaD0Djqxo5GptsGvLOBsqmk=,iv:BMZ4gcZbKdc6+fkOx2PGMJAfKIVkhJ9glMAO/E7OTAM=,tag:JAhGz7YnN/Y0uMN26oKCsw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:3DikLTky3cGuKeEDVDQhdt/uw0A=,iv:xvAs0LP2keDffR4CTNkbXapNUJXu/tYE2P1hO0ehY3g=,tag:YafNe79vJJdbEJkuhf8RQg==,type:str]
sops:
    age:
        - recipient: age1xrxcj4d3zj8pnnyysph9qpve8stj8wr9dk7y0nq8ns4nukcruyxq5cc5at
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZSHJnbDJLNUNUR0ExRWpY
            bjVsRTdrNlhtekhxQjRGd3dueDFZTnErMVdVClI3YytLYU9CV2Z5Unh6TU5NT3FI
            U2pQVGI4dE1zSERNK2RWcjl2TnJFUEkKLS0tIFhXdHNTQzZ4RmhXeVlGbHpQam5h
            WE9FYU1McFFBL21DK2kyb0lsSnVhUlEKMUjZwD/1kZwqu/arGcGJoRsuKYPsek0G
            xik7MWxby+9U6Fkngw5CaZxQGI6XLgbmdVPN+hUJ+UNmKS5DMp/e4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-06T07:51:04Z"
    mac: ENC[AES256_GCM,data:8G9p7Ph4M6+q1QCll560pyQ6QdQZsiuPLkfrKKXp6uwnDi6Ur7EmSgEnC8KfGt2TqrvsmKwxbU32wStsQ8kNyBJWQNZ/6raHB9Z5TdkWq9AsT5SBy56aJonrSRDraR/or3Rm1rCEbtdAla+i/wMmIYEBRRIbdYMD9f4RM3HDfT0=,iv:vi5RJraafa1pI/o9SAuxZedO8+TmLwVNYck1hvot1R0=,tag:t2n9alGurKDtL+31mCWlIg==,type:str]
    pgp:
        - created_at: "2024-06-22T10:58:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DopS/VjtMxJoSAQdAGyo6efV031zgz1kcWhfecsXxcbOI6lYDDR7CrVUZORsw
            8Hhnyd7izF2Z8dPSQLvI/FL0ydiNE6DPnFBtxg9eyxO3IsaqskNnyBtT48626hXF
            0l4BdHWZHNPigfJEa+cAVrazSClleI4Ucs8KRljxwP21A/ukA3Ypj6a1cmWtQUer
            b04SBWJ2eMOtvk0wq8dOqnVVZI3P1p2rs+05eZv2o0vK13Zrx9I0Mp5AP3kwN1eW
            =lBFI
            -----END PGP MESSAGE-----
          fp: 86170CE5CB464ADDC6BE8E597450F180356132B6
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
