---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: fix-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-added-large-files
        args: [--maxkb=2048]
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.10
    hooks:
      - id: remove-tabs
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
        args: [--strict]
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5
    hooks:
      - id: shellcheck
        args: [--severity=error]
  - repo: https://github.com/ansible-community/ansible-lint
    rev: v5.1.3
    hooks:
      - id: ansible-lint
        files: ^ansible/
        always_run: false
        entry: bash -c "cd ansible/ && exec ansible-lint --force-color"
        additional_dependencies:
          - ansible>=4.8,<4.9
  - repo: https://github.com/k8s-at-home/sops-pre-commit
    rev: v2.0.3
    hooks:
      - id: forbid-secrets
  - repo: local
    hooks:
      - id: kustomize
        name: Kustomize
        files: ^cluster/
        entry: hack/kustomize.sh
        language: system
        pass_filenames: false
