---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ${APP}
spec:
  sourcePVC: ${APP}
  trigger:
    schedule: 0 */12 * * *
  kopia:
    accessModes:
      - ${SNAP_ACCESSMODES:=ReadWriteOnce}
    cacheAccessModes:
      - ${CACHE_ACCESSMODES:=ReadWriteOnce}
    cacheCapacity: ${CACHE_CAPACITY:=2Gi}
    cacheStorageClassName: ${CACHE_SNAPSHOTCLASS:=openebs-hostpath}
    compression: zstd-fastest
    copyMethod: Snapshot
    moverSecurityContext:
      runAsUser: ${PUID:=568}
      runAsGroup: ${PGID:=568}
      fsGroup: ${PGID:=568}
    repository: ${APP}-volsync
    retain:
      hourly: 24
      daily: 7
      weekly: 5
    storageClassName: ${STORAGECLASS:=ceph-block}
    volumeSnapshotClassName: ${SNAPSHOTCLASS:=ceph-block}
