---
kubernetes:
  children:
    master:
      hosts:
        k8s-node-1:
        k8s-node-2:
        k8s-node-3:
    worker:
      hosts:
        k8s-node-4:
        k8s-node-5:

unifi_controller:
  hosts:
    sun:

storage:
  hosts:
    singularity:

printer3d:
  hosts:
    curiosity:

pi:
  hosts:
    curiosity:
    ursamajor:
