apiVersion: v1
kind: Secret
metadata:
    name: authelia-init-db
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:PFLUpBNJlmE=,iv:46bFJs9Mikx+yTmYBCytaKJ5r2XyqjA5Ku61MK9kv3k=,tag:DSDqyMor596d+zuLYWY41Q==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:imdYY4Z8/MWp33mKcKZwCFxixbQJVGXn2G+U8V1HutmwaBx9mVJtFQ==,iv:SnVYPfWwqiGRPrxqH4VVjGAfa4kpaiO9ZKeOplH6BcA=,tag:kNCJyn246lakRt+KUQGoCw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:TkE+hK05PVg=,iv:17ScY1UURKiwK/K1XZjuLHQ/gQnE/vq3FmRhpSeC128=,tag:PIkOEqD92uYYCV21SWub+w==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:0V67XIsWECah3CSqSGZCLu5JUg8=,iv:b6xIZv0y99EC6cs9hm4aAnpiMOYnWUa1Ukgp6z1WWFc=,tag:tq10gwmDnjw3ay4oOKNl7A==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:sxgp93+SiTQN4nszIsMQRKkhy54=,iv:d9e3I0DRYsa9fRepyp5Poet68HZenu4kXeqCVT4JC7Y=,tag:ByxxIsDoctIlmd2b3h1urA==,type:str]
sops:
    age:
        - recipient: age1xrxcj4d3zj8pnnyysph9qpve8stj8wr9dk7y0nq8ns4nukcruyxq5cc5at
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPOWl1VUNQS1NQemYrUkh0
            VWpjUktMSHZJZzAveG0yc09jUmd5Uk93ZDJrCkxZZy9vL01HMHN3QjBQVTliUEZl
            UDBXYTBzWnhNTnJFNjFXeTh1YmVPbnMKLS0tIHVHbTdGcjFPSUtOL0lSdUNlZ2Mv
            TWEvT3pUMllWS0l3a1pHUVk1di9QVWMKklXVvo0Iocq7+u+nDxnLzUAVQWlFgjK7
            I6uGMJXwFZAuOKNEpbBLFGs+89iFaUPARhta3ufk0DwSDmfLpi6fog==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T19:13:29Z"
    mac: ENC[AES256_GCM,data:peInzSKG9Ke5kDCMOlMwHy0n9ic/tsr8EcNbpulmpTmgDS8pmM6oyibapVpQTWkbjpvDS5ihLlMKxDrL/jBWhPE09YfAu3YRPZnSfcHNGJ91TV0HcDqb7rsM7xVbP664WDSx934hB6Xy3zt9eMC0Pp/nnTirY/Yd574Vz0OdbBo=,iv:vESpFY+KLDCl+pA7TlXMMcWw29KuMzdrHDgV1BlsrFU=,tag:8aH+w8kDJyrluvgvHkTGOQ==,type:str]
    pgp:
        - created_at: "2025-11-09T19:12:54Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DopS/VjtMxJoSAQdAI93R4w0rU7njWAoEiCNRVSvORw+vjKObt+KYNvKpR1kw
            owfU092c6Kxe4cjNT4KHbl+kJoxq6yIMymRzlbQdjoOdGhVJSivPbuded6ixxJpO
            0l4B/4Tdx/brdZX2xY8XhG1hkO1Mwx4tDnEO+ZiD7OZiKwyjmFPCFHatOC9B75pW
            dm9hCdQMZF5G/F4jUDaFpF4k4F7zsZx1133aJVa7nIRu4/z35hLaUh1L7b7Ig8JZ
            =YFOx
            -----END PGP MESSAGE-----
          fp: 86170CE5CB464ADDC6BE8E597450F180356132B6
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
