---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - angelnu.yaml
  - authentik.yaml
  - backube.yaml
  - bitnami.yaml
  - bjw-s.yaml
  - blakeshome.yaml
  - coredns.yaml
  - dex.yaml
  - diaoul.yaml
  - emqx.yaml
  - external-dns.yaml
  - grafana.yaml
  - hajimari.yaml
  - ingress-nginx.yaml
  - intel.yaml
  - jetstack.yaml
  - k8s-gateway.yaml
  - kasten.yaml
  - kubereboot.yaml
  - kubernetes-sigs-descheduler.yaml
  - kubernetes-stable.yaml
  - kyverno.yaml
  - longhorn.yaml
  - node-feature-discovery.yaml
  - metrics-server.yaml
  - oauth2-proxy.yaml
  - project-calico.yaml
  - prometheus-community.yaml
  - piraeus.yaml
  - rook.yaml
  - runix.yaml
  - stakater.yaml
  - strimzi.yaml
  - traefik.yaml
  - vector.yaml
  - vernemq.yaml
  - vmware-tanzu.yaml
