---
calico_state: present
calico_installation:
  cidr: 10.42.0.0/16
calico_bgp_configuration:
  as: 64513
  service_cluster_ips_cidr: 10.43.0.0/16
  service_external_ips_cidr: 10.44.0.0/16
calico_bgp_peers:
  - name: router
    ip: 10.0.1.1
    as: 64512
