apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-cloudflare
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:sDWSeQ2MfJLroB3YoR8JnjTJdurCsj1lGm52pB0yfZAMAGxynkHWhw==,iv:5zvEQyOHN5ObC9vdjSoU5dey+1lvRBZMnIFzMU7CZwE=,tag:SbMwYfS9e8aHmxtSfuNbgQ==,type:str]
sops:
    age:
        - recipient: age1xrxcj4d3zj8pnnyysph9qpve8stj8wr9dk7y0nq8ns4nukcruyxq5cc5at
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQXFLU2NXY1RKb1EyTUhH
            dS9Qc1o5Q0FrR0pBcis1Nmk5ZDlsYXhIVjM4CmV0MmlTWjZUb1hZcERNcXlpNVBL
            V2xDOTJ1WUtGbllWZlR3YlNoWG5jcUEKLS0tIDROVFRNeTJqNHowWjZMb1NzK0lK
            UGtESVBHQ3pvL3gyZEo4OEt3RTBJaTAKvfVjF9i8xgicCm17pMpTuHBmovu6GPTR
            nk4/J5GInLFUvrVnG+cR0feMXZ3WR9K/wCSUFu5bLOzAlp46iTryqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T19:57:01Z"
    mac: ENC[AES256_GCM,data:Q2nZvVQdg0m1/5BYDCTsAvTSt0LlfKoYa68+R2VhPogJ8euna/oXFJNftf45+T8j+ttCHDzoksiFZfWG7x0S++zn5lGx6Z1yaGyTJIOTaxdUKYco6GTtdyMqP4QOmhW6fev5vGVTqooiYq3R4axymtkCbQYNn1xkwP1hCC3GwAU=,iv:N3gATvVq/rOGurRzuTCUWpIG+7iB3BEoKnAhEv9JarA=,tag:bauuA4y1cccUTgALzCN9xQ==,type:str]
    pgp:
        - created_at: "2024-06-20T21:05:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DopS/VjtMxJoSAQdAnqQFdIbvUbToBHKWVG6F7IbglX7i3CyZs9/yT/l8fUgw
            6y4zmEdgGKCupOVaOYlsDWtLonO11f0uKpNwAEBYzSzNWuRSMvQ1wV+rR42rII00
            0l4BfsoEVceVGMuqagNzwU6dbtEzWjp0bgBsIXveNWWcjbI2FSCIZvVmd8OaFPj+
            9a+rZGZfxIQsDogSNoA4JYewYO1QG6mLpIjN+UP+dfaUa2AHBxZiGjvhwQW8n57p
            =gV82
            -----END PGP MESSAGE-----
          fp: 86170CE5CB464ADDC6BE8E597450F180356132B6
    encrypted_regex: ((?i)(pass|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
