---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - db
  - default
  - dev
  - flux-system
  - calico-system
  - kube-system
  - networking
  - monitoring
  - home-automation
  - media
  - velero
  - vpn
