---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kube-prometheus-stack-crds
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/prometheus-community/helm-charts.git
  ref:
    # renovate: datasource=helm registryUrl=https://prometheus-community.github.io/helm-charts chart=kube-prometheus-stack
    tag: kube-prometheus-stack-48.3.1
  ignore: |
    # exclude all
    /*
    # include crds directory
    !/charts/kube-prometheus-stack/crds
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kube-prometheus-stack-crds
  namespace: flux-system
spec:
  interval: 30m
  prune: false
  sourceRef:
    kind: GitRepository
    name: kube-prometheus-stack-crds
