---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pv
  - pvc
  - double-take
  - emqx
  - esphome
  - frigate
  - home-assistant
  - node-red
  - zigbee2mqtt
  - zwavejs2mqtt
