---
collections:
  - name: ansible.posix
    version: 2.1.0
  - name: community.general
    version: 12.1.0
  - name: community.docker
    version: 5.0.3
  - name: community.kubernetes
    version: 2.0.1
  - name: community.sops
    version: 2.2.7
