---
collections:
  - name: ansible.posix
    version: 2.1.0
  - name: community.general
    version: 11.4.1
  - name: community.docker
    version: 4.8.2
  - name: community.kubernetes
    version: 2.0.1
  - name: community.sops
    version: 2.2.6
