---
collections:
  - name: ansible.posix
    version: 1.5.4
  - name: community.general
    version: 7.0.0
  - name: community.docker
    version: 3.4.5
  - name: community.kubernetes
    version: 2.0.1
  - name: community.sops
    version: 1.6.1

roles:
  # workaround for https://github.com/PyratLabs/ansible-role-k3s/issues/196
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s.git
    version: v3.3.1
