---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - pv
  - pvc
  - airsonic
  - bazarr
  - flaresolverr
  - jackett
  - jellyfin
  - lidarr
  - nzbget
  - photoprism
  - prowlarr
  - qbittorrent-vpn
  - radarr
  - readarr
  - readarr-audio
  - sonarr
