apiVersion: v1
kind: Secret
metadata:
    name: lldap-init-db
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:5ZSW4Ew=,iv:WPPoA1EQ6DWkm9l/aoWXLk/VZ4tss02nXhodWokaqfA=,tag:0Wb9qSQJfL/MEq/D77DjdQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:7ZfS+hnv67ierrgLL+2cTXXrdupdD6xKbb5jhs0hhuxB3jv2kDR2Rw==,iv:qJFBnSCQxdKi4pIG4gEep3bmGjFpTZhpafX3O3Xxmng=,tag:IloEPur8qA95PZ//UAWRvg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:CwgBy6M=,iv:2tehSAPVwkcXh20Qtkux+pOoVgYXkth+bC12LSvgCsc=,tag:WYakbZla/1epobxcFB8cng==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:AyQvAzAyTSwCXA1nKSe7Qd4kbpo=,iv:iBJMSa8lfEPEJKCMu7dK0twyw86B8VNt1s57/hWqHvQ=,tag:68Ycy9KWVXVXQ0FshEOZxQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:S3QmzuKQsGj1RvLGyscB8DFiTlc=,iv:AWnNChKGlUkUXPIRxGx5X2x+z2FXiC90EGpWuN43nos=,tag:VjJNVz93jiGS2lPu2LicLw==,type:str]
sops:
    age:
        - recipient: age1xrxcj4d3zj8pnnyysph9qpve8stj8wr9dk7y0nq8ns4nukcruyxq5cc5at
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXU0Z1Nm00UkI0NmEvdVJr
            YkpGYTlvL1RaZHkwSjkrSlBqaTNXTS9aaVd3ClN1QXlwUlgzV0pVcXRuR3lEZ1Ns
            UXlyZGpOeHk5dlNkSTNhR3JDT3pwaW8KLS0tIFhhUGt2RExaZXpzZi9sOVBoSjhS
            a3hGckNMZityTE8xT3E4YXRzcWtGVkEKb9WhYj+lndmNF2dvdJVWqnyoBEKy4HlM
            qmEmjFuFsyj2cJFGS5bLGgsIv/lu/U3bzCQ76OJyP1YumsxIL3l8WQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T19:14:40Z"
    mac: ENC[AES256_GCM,data:3OeviZslsvd+kSWGcNP8Pelddt7oKF7wtcBZ4H3LD3yRb7iDMeOYYVSKQI4KVdDSUar7g6Ncp1FnTeACg/KA113tF7tP2srXQhLQcw7YvOQ8tmEJPfoQZWmbNaJw1+bD9t5yqkN92xkdoNCzwhS/y7e7Qh62lh4vuUeT4yH1hC4=,iv:DyVQFT+z1hphEE22WbZvVpVCEHLQsABDE2WXV4nU2pE=,tag:8ESKIBmsvjQvTGS/89bLvg==,type:str]
    pgp:
        - created_at: "2025-11-09T19:14:11Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DopS/VjtMxJoSAQdAy6r0v+ungs2URuQzUswOLfxH2wzTY4NJvkEc00uE+V4w
            3QF2Gtd+kqlrvSaILQ2VtEXXDMgdHcwdfGLqAFnu1qOJ7vfCVhUVL3IpZj8rEDzJ
            0lwB5uHBVo+ueGZLtdlPafKC0CReFw+EszHP/Tyj7hdSWYis5G7vYHLF8HvA5Rwm
            4uJwiH7yBTSWN0GpBEKnqet4p6OnfMyR31ArrPnLcNiwjaTW7kySnzaxrXaCBw==
            =s9ej
            -----END PGP MESSAGE-----
          fp: 86170CE5CB464ADDC6BE8E597450F180356132B6
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
