# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: lldap
stringData:
    #ENC[AES256_GCM,data:piFE4xou,iv:kJ5jQKuZcO39m+7w7mSaQ9TZj+sG7SGfgiee+siAVX0=,tag:ejVQR0jA3v2y1MWbG2+R7w==,type:comment]
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:KweoNi0dokbQNI97DPzx2NGlX/b0XJb9Twv95Pdxj8w=,iv:Hkq6qaIX0PJm2UkYe9pYAui7VJ5PcIzZTNsZ/CJur5w=,tag:iz2ebZR4fHRokm2Qa0nVsw==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:qW7z+QnETPbdZOT4mr6XSI0IDus=,iv:WudDACKzIHkfmRObLpHlKW3ZIGkp1KR5kyQMLuPfB14=,tag:z5E1J5Ois38zyg1BHT1FCg==,type:str]
    LLDAP_DATABASE_URL: ENC[AES256_GCM,data:psjBi+RWkloyrn5MifHoa7KG52r2YC/Eczc7Boo7V+nOe95eFNPSKB8Xvxuld2tvSozx2kdprvvBPR1Wf0OiAK7Wxxt6V0oOkIRjc7dZgK7z76uk,iv:3Iqvaq5/GychLLA7sjdMKzf2Ob9/ScCfKizdfmi/RV4=,tag:x+yjSIem76n4Edk2DeprOg==,type:str]
    #ENC[AES256_GCM,data:2jdzWIMs8asJGlyMvmk=,iv:tMMy8fdSQdleV2JEa+9ywxMgpmCKSwcjVNbuNKmKKx0=,tag:2nn/jNANy/RZAbi0c9lCJw==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:PyuRjeM=,iv:LT1y9zAng0EMP0az5QMJ6INjBKR3E8QYxASPQgiHKAY=,tag:euA63yVolIIUKhVwdj9rJg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:yFFPrO3K1CvfsBGLCV+QS+ZhsPsp5AA9fGgOEhNv9L23jUDk5AYFrQ==,iv:lOcRRZL/X8zhdIGsNtt3f+O3MJC8WJifcZQSUalZADw=,tag:+pOPVCekmIJ43jgiwHfUqA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:DvAmIwY=,iv:BND5R1eeJRT+R2JSGxXBfUgvUby5O60tMrWgpgAtq0I=,tag:nG/oN8ZIdR0UORuNHWPQ0Q==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:PAPcV8ZucPKEZGtHDME2ZWEvX+U=,iv:UkOCs8Z86Gz5Jh7wdHq397kAKpPKXu1LUHhOWMW/xH4=,tag:YwzMF7Wj7y4w9VDgTnJaNw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:nbQFu1QqT3zbedi79YSE3j28RSw=,iv:ZiT648DvPI3I5MzTmFgvP4mrbcn23ZepobljO8YvXBw=,tag:4XSDyb2bHO9dg5+NKPfVlg==,type:str]
sops:
    age:
        - recipient: age1xrxcj4d3zj8pnnyysph9qpve8stj8wr9dk7y0nq8ns4nukcruyxq5cc5at
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArM2ZPNENON1JyVytMWlNW
            WnprUHBwbHI3K0JCa0pwZE9Ddy9YaS93OGk0CnhWdW41UHdnS01qZFQ3OUE1WGtv
            VDkrcnM1R1ZPNVpIZlhITTZmbGhyeTgKLS0tIDExT0dEeEM1WVVqWVhBYW9ueHE0
            bTRrNWNkaVhpMzJBa1orcUJ3ZkZhMVEKyWHYTeVh3smn+KAU4CXSrJwTxMVTkk5z
            ZFr4Xn3q4v1G1N8JqR7oQWYUzrdwN6YtbV3G6xEMV31hFuv6t2zJhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-06T07:55:14Z"
    mac: ENC[AES256_GCM,data:vdbhdkfNXkyiIuKWqe7o7I50SSOnsj0W2rBF7D+EO1AXrpPXLZ1LzNS2cgpmewjyDj2OCG+5pqTBgISZQasZ/sUYRs2TXLCzwQURNiNGYZjX97nF7uaB6GclJrADIgO9Ni3jLXmVQgp0fleNu8BpyDE/54ZAE+t1TlTDmq1jsg0=,iv:gEoXS9/njm8K1ZiK+TUF+SDnFjEbOHrhb/akHWrw4vE=,tag:NlRr/LL19VLLnYrkpwxAmg==,type:str]
    pgp:
        - created_at: "2025-09-27T14:09:43Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DopS/VjtMxJoSAQdAteFIbEQySfvBmv6weqm1HCEyTQUhfJ38MFb0/W8k2xMw
            yYVkDi5aiN/n5BfD3zwrnfAB658eljthz9xsUBagDMQGaJQKiV8khQBe4Rzn9K5X
            0l4BlQFcQBmGdbjBa8X+3ow3nr0DG3TB6KmdgGJeQJxfSZ4ywmo+GRMKJlasUekF
            R5AhXrQ9XTdTtuaueiTLtqRJ8nbhqiReczFvh83gxdY1QLCHrTVHJuOSa+MnrSa0
            =JhkG
            -----END PGP MESSAGE-----
          fp: 86170CE5CB464ADDC6BE8E597450F180356132B6
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
