apiVersion: v1
kind: Secret
metadata:
    name: lldap
stringData:
    LLDAP_JWT_SECRET: ENC[AES256_GCM,data:KweoNi0dokbQNI97DPzx2NGlX/b0XJb9Twv95Pdxj8w=,iv:Hkq6qaIX0PJm2UkYe9pYAui7VJ5PcIzZTNsZ/CJur5w=,tag:iz2ebZR4fHRokm2Qa0nVsw==,type:str]
    LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:qW7z+QnETPbdZOT4mr6XSI0IDus=,iv:WudDACKzIHkfmRObLpHlKW3ZIGkp1KR5kyQMLuPfB14=,tag:z5E1J5Ois38zyg1BHT1FCg==,type:str]
    LLDAP_DATABASE_URL: ENC[AES256_GCM,data:psjBi+RWkloyrn5MifHoa7KG52r2YC/Eczc7Boo7V+nOe95eFNPSKB8Xvxuld2tvSozx2kdprvvBPR1Wf0OiAK7Wxxt6V0oOkIRjc7dZgK7z76uk,iv:3Iqvaq5/GychLLA7sjdMKzf2Ob9/ScCfKizdfmi/RV4=,tag:x+yjSIem76n4Edk2DeprOg==,type:str]
sops:
    age:
        - recipient: age1xrxcj4d3zj8pnnyysph9qpve8stj8wr9dk7y0nq8ns4nukcruyxq5cc5at
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArM2ZPNENON1JyVytMWlNW
            WnprUHBwbHI3K0JCa0pwZE9Ddy9YaS93OGk0CnhWdW41UHdnS01qZFQ3OUE1WGtv
            VDkrcnM1R1ZPNVpIZlhITTZmbGhyeTgKLS0tIDExT0dEeEM1WVVqWVhBYW9ueHE0
            bTRrNWNkaVhpMzJBa1orcUJ3ZkZhMVEKyWHYTeVh3smn+KAU4CXSrJwTxMVTkk5z
            ZFr4Xn3q4v1G1N8JqR7oQWYUzrdwN6YtbV3G6xEMV31hFuv6t2zJhQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-09T19:14:43Z"
    mac: ENC[AES256_GCM,data:wq/6kkCwImRQoPamuqD9b1yVFm+cvqEnG6iu7rBNX1QygR6mnejHfF3FxDUgJJ2+vrd6wfXL3+yfltKIV3uLqTSJoLPbYC1YSoqFB/rN66dFmsnCMl0rsw7ZIJd+dzO0i/24Awnncvg2HOAe+qYnsmuFpdDDkoTN5WNuVmgrZI4=,iv:3Nh8ptv7a43vibpFqHmVRnAMufKIscEMCvbUXxKT/+c=,tag:NKX416P9DmLhKw6tUf1UwQ==,type:str]
    pgp:
        - created_at: "2025-09-27T14:09:43Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DopS/VjtMxJoSAQdAteFIbEQySfvBmv6weqm1HCEyTQUhfJ38MFb0/W8k2xMw
            yYVkDi5aiN/n5BfD3zwrnfAB658eljthz9xsUBagDMQGaJQKiV8khQBe4Rzn9K5X
            0l4BlQFcQBmGdbjBa8X+3ow3nr0DG3TB6KmdgGJeQJxfSZ4ywmo+GRMKJlasUekF
            R5AhXrQ9XTdTtuaueiTLtqRJ8nbhqiReczFvh83gxdY1QLCHrTVHJuOSa+MnrSa0
            =JhkG
            -----END PGP MESSAGE-----
          fp: 86170CE5CB464ADDC6BE8E597450F180356132B6
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
