---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Kubeconform

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - kubernetes/**
  push:
    branches:
      - main
    paths:
      - kubernetes/**

jobs:
  kubeconform:
    name: kubeconform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install Kubeconform
        shell: bash
        run: |
          # renovate: datasource=go depName=github.com/yannh/kubeconform
          go install github.com/yannh/kubeconform/cmd/kubeconform@v0.7.0
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Run kubeconform
        shell: bash
        run: |
          scripts/kubeconform.sh kubernetes
